# Generated by Django 3.1.4 on 2020-12-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_likers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="nr_likes",
        ),
    ]
