# Generated by Django 3.1.4 on 2020-12-18 17:08

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_remove_post_nr_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
