# Generated by Django 3.1.4 on 2020-12-18 17:08

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_auto_20201218_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likers",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
